<?php 

/**
 * Parse module info file.
 * Copied from Drupal 6.x core.
 */
function deproj_set_version($filename, $ver) {
  $info_file = file_get_contents($filename);
  $start = stripos($info_file, 'version');
  $end = stripos($info_file, "\n", $start);
  $comment_start = (int)stripos($info_file, ';This code is generated by deproj util.');
  
  // file was updated by deproj earlier
  if ($comment_start > 0) {
    $comment_end = (int)stripos($info_file, "\n", $comment_start);
    
    $part1 = substr($info_file, 0, $comment_end);
    $part2 = "\n";
    $part3 .= 'version="' . $ver . '"' . "\n";
  }
  else {
    $part1 = substr($info_file, 0, $start);
    $part2 = substr($info_file, $end + 1);
  
    $part3 = "\n\n";
    $part3 .= ";This code is generated by deproj util. Change it, only if you know what you are doing.\n";
    $part3 .= 'version="' . $ver . '"' . "\n";
  }
  
  $res = $part1 . $part2 . $part3;
  
  if ($fd = fopen($filename, 'w')) {
    fwrite($fd, $res);
    fclose($fd);
  }
  else {
    echo 'I/O .info file error: ' . $filename;
  }
}
//deproj_set_version('prisof_base/prisof_base.info', '00');
$info = deproj_set_version($argv[1], $argv[2]);
